version: '3'

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: "bitnami/kafka:latest"
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producer:/usr/src/app
     
  consumer1:
    build: ./consumer1
    container_name: consumer1
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumer1:/usr/src/app
  
  consumer2:
    build: ./consumer2
    container_name: consumer2
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumer2:/usr/src/app
  
  consumer3:
    build: ./consumer3
    container_name: consumer3
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumer3:/usr/src/apps

  consumer4:
    build: ./consumer4
    container_name: consumer4
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumer4:/usr/src/apps

  consumer5:
    build: ./consumer5
    container_name: consumer5
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumer5:/usr/src/apps
